### ISSUE TITLE
How to use the script to convert the KEGG module file to <module_id>.kk?

### ISSUE THREAD

**Issue by jinhao94** [Matteopaluh/KEMET#15]
Hi,
Thank you for the excellent tool! It's very helpful to me!

I have a question for you. Do you have a script or program to convert the KEGG module file to <module_id>.kk?

The KEGG module file I mean here is:
[M00001_Glycolysis_(Embden-Meyerhof_pathway).txt](https://github.com/Matteopaluh/KEMET/blob/main/KEGG_MODULES/M00001_Glycolysis_(Embden-Meyerhof_pathway).txt)

I'm asking because I want to assess the completeness of some KEGG pathways in the bacterial genome and I can't process the KEGG htext format files in bulk (Unless convert them manually).

I hope you have a solution for me...

I really appreciate any help you can provide.
Hao Jin

**Comment by Matteopaluh** [comment]
Hello and thanks for the nice words!

There is a script to do what you ask but it's not ready to be shared, as it is not completely bug-free. It possibly will be shared at some point, as it would make it easier to automatically update to newer KEGG releases.

At the moment the `.kk` files have been generated with this script and some had gone manual curation.
Moreover for the latest KEMET update (#14), all `.kk` files undergone quality checking and have been updated to KEGG last release from January 2023, which should make them generally error-proof for now.  

**EDIT: M00001 specifically was probably edited again after last update (I'll correct it asap).** 

The `.kk` files that KEMET is using are found at `KEMET/KEGG_MODULES/kk_files/`.
Regarding custom modules, or modules that will recieve any updates from newer version, it still relies a little on curation (see relevant info [here](https://github.com/Matteopaluh/KEMET/wiki/3-KEGG-Custom-Modules-analyses)) .

Best,
Matteo

**Comment by jinhao94** [comment]
Hi Matteo,

Thank you for your prompt response.  

Looking forward to the launch of this script ☺

Cheers！
Hao Jin

**Comment by Matteopaluh** [comment]
As per last commit, module M00001 was updated, one KO was left out by mistake.

Hope your analyses will be insightful!

Cheers,
Matteo
