### ISSUE TITLE
Incorrect recognition of MAG filename

### ISSUE THREAD

**Issue by SarahIsme** [Matteopaluh/KEMET#16]
Hello, thanks for developing this useful tool.

I put co_metabat2.1.fa, co_metabat2.12.fa, co_metabat2.100.fa, co_metabat2.199.fa in the `genomes` folder at the same time, and their annotation files are also all placed in the `KEGG_annotations` folder.
If I run `kemet.py -a eggnog --skip_hmm genomes/co_metabat2.1.fa`, only reportKMC_co_metabat2.199.tsv is displayed in the 
 `reports_tsv` folder, but co_metabat2.1.ktest, co_metabat2.12.ktest, co_metabat2.100.ktest, co_metabat2.199.ktest are displayed in the `ktests` folder.

Can you help me with this problem?

**Comment by Matteopaluh** [comment]
Hello Sarahisme,

I tested the code with a similar test-case and after a minor adjustment I had it to work.
I'd ask you to download the newest version of this repository (or at least the `kemet.py` script) and try again!

New code should handle better filenames with several extensions. The initial script design did not include cases in which extra dots (".") were included in genome names.

Let me know if last commit fix the problem for you as well, so to close the issue.

Best regards,
Matteo
