### ISSUE TITLE
Dealing with different MAG completness?

### ISSUE THREAD

**Issue by michoug** [Matteopaluh/KEMET#2]
Hi,
Very nice tool that I'm excited to try
I wanted to know how (if it does) the software delt with different MAGs completeness
Best
Greg

**Comment by Matteopaluh** [comment]
Thank for the early support Greg!

KEMET works fine with every MAG, genome, or any sequence really, regardless of their completeness, as long as a proper KEGG annotation and the nucleotidic FASTA are provided.

The task of summarizing the metabolic potential with KEGG Modules works straightforward for every annotated sequence, and it provides an easier organization of the KEGG annotation.
In the paper (https://doi.org/10.1016/j.csbj.2022.03.015) we actually tested the following tasks with good quality MAGs, to prove the genome-scale models improvement. Nonetheless, the functions don't act differently in the presence of a different completeness level.

Based on the desired downstream analyses, with KEMET it's possible to search for diverse subsets of KEGG orthologs using hidden Markov models profiles. We though it could be biologically relevant to look for genes missing from almost complete functions (viz. KEGG Modules), as well as some specific functions or genes of interest.
The insights obtained this way can be used in combination with genome-scale models, or can just prove the presence of potential functions in a qualitative way.

Hope this helps in clarifying your doubt! If it did not, feel free to re-open the issue.

Best,
Matteo
