### ISSUE TITLE
Custom Modules?

### ISSUE THREAD

**Issue by michoug** [Matteopaluh/KEMET#8]
Hi,
I saw that the README indicated that custom modules could be added.
Should they just be included in the `kk_files` folder, or do they need to be included elsewhere?
Cheers
Greg

**Comment by Matteopaluh** [comment]
Hi Greg,
Yes, you're totally correct: custom modules should be included in the `kk_files` folder.
Those files have a specific format that was generated via a script and a few modifications from the original KEGG MODULES entries.

Any user can include other modules by generating a file with ".kk" extension and the following format.

As an example, below are some indications as present in [M00023](https://github.com/Matteopaluh/KEMET/blob/main/KEGG_MODULES/kk_files/M00023.kk).

```
M00023_Tryptophan biosynthesis, chorismate => tryptophan
K01657, K01658, K13503, K13501, K01656, K13497
K00766, K13497
K01817, K24017, K13498, K13501
K01656, K01609, K13498, K13501
K01695, K01696, K06001, K01694
COMPLEXES_LIST
K01657+K01658, K01695+K01696, K01695+K06001
```

### 1st line (indications that appear in the report files):
<Module_ID>_<longer_module_name>

### 2nd until end/extra lines:
sequential KEGG orthologs alternatives for a single step, separated by a comma.
### Extra lines (in case of more complex reaction relations):
- A "COMPLEXES_LIST" line enables multi-genes relations informations (e.g. K01657+K01658 for the first step of the exemplified module).
- An "OPTIONAL_LIST" line includes KOs which are not mandatory for considering a module step complete, but KO presence/absence is still indicated in the report files.

Thank you for your interest in KEMET!
Cheers,
Matteo

EDIT:
[here](https://github.com/Matteopaluh/KEMET/wiki/3-KEGG-Custom-Modules-analyses) for the wiki page listing all Module indications, derived from this issue answer.
