### ISSUE TITLE
"ktest" file error - due to file naming convention

### ISSUE THREAD

**Issue by ggezwp123** [Matteopaluh/KEMET#9]
I met an error.
$./kemet.py genomes/x23.fna -a eggnog --skip_hmm
###
Traceback (most recent call last):
  File "/root/KEMET/./kemet.py", line 2440, in <module>
    if ktest in sorted(os.listdir()):
NameError: name 'ktest' is not defined
###
What  is the problem?

**Comment by Matteopaluh** [comment]
Hi,

I believe the error could be due to not adding a properly named eggnog annotation file in the `KEGG_ANNOTATION` folder.

In the above case, it should be called `x23.emapper.annotations` (i.e. the eggnog output extension, with the name of your genome/MAG of choice before it).

Let me know if maybe renaming files solves it!

**Comment by ggezwp123** [comment]
$./kemet.py genomes/x23.fna -a eggnog --skip_hmm
###
Traceback (most recent call last):
  File "/root/KEMET/./kemet.py", line 11, in <module>
    from reframed import load_cbmodel, save_cbmodel
ModuleNotFoundError: No module named 'reframed'
###
I added a eggnog annotation file named x23.emapper.annotations in the KEGG_ANNOTATION folder.
But I still met a new error

**Comment by Matteopaluh** [comment]
Great, so I believe the first one should be considered as solved.

```
from reframed import load_cbmodel, save_cbmodel
ModuleNotFoundError: No module named 'reframed'
```

^ this states that you're not using a conda environment with Reframed installed, as stated in the installation info:
You could solve this by properly following the indications, i.e. running `pip install reframed` on your terminal, with the kemet conda environment active.

**Comment by ggezwp123** [comment]
I forgot that I have reboot my virture machine. HAHAHA!
My problems have solved. THANK YOU!
I believe this program is a powerful and convenient tool!

**Comment by Matteopaluh** [comment]
Good! Glad all was sorted out easily.

And thanks a lot for the kind words, hope more people will find it useful as well!
